### ISSUE TITLE
Octopus: le sommeil

### ISSUE THREAD

**Issue by nobrakal** [IP7/articles#2]
On a à faire

Deadline le 15 avril

**Comment by Peaupote** [comment]
https://github.com/IP7/articles/blob/master/google-deep-dream.md

**Comment by nobrakal** [comment]
Il nous reste deux jours, faut se bouger là.
Des gens pour relire ?

**Comment by nobrakal** [comment]
@elusyo  ? 
@FauconFan  ?

**Comment by FauconFan** [comment]
C'est très bien. C'est marrant de voir les choses comme ça ^^.

J'ai juste 2 commentaires:

- Le fait de retourner un réseau de neurones est peu commun, on le comprend parce qu'on sait ce que c'est, et qu'on arrive très bien à représenter le `retournement` dans un CNN. Je crois que le terme renversé ou inversé est plus adapté.
- Je trouve ça un peu osé de mieux comprendre le rève humain, grâce au rève machine. En tout qu'ouverture oui fin voilà, j'ai un à priori, mais si vous l'avez pas, c'est négligeable je pense...

Bisous

**Comment by Peaupote** [comment]
L'ouverture est assez osée oui; mais il faut rêver le lecteur bon sang !

**Comment by FauconFan** [comment]
Oh, tu as le sang chaud x). C'est bien ^^. J'aime, j'approuve

**Comment by nobrakal** [comment]
Merci @FauconFan !

Le dernier paragraphe ne me convient pas trop, il y a plein de répétition du mot "rêve" et il parle de *Deep Dream* sans avoir dit avant que c’était le nom de l’équipe....
