### ISSUE TITLE
Octopus: Le sexe

### ISSUE THREAD

**Issue by nobrakal** [IP7/articles#4]
2300 caractère sur la pornographie.

Deadline le 20 mai

**Comment by Peaupote** [comment]
Qui veux bosser dessus ? Je peux faire un truc, là tout de suite je suis pas hyper inspiré.

Le sexe c'est sous entendu l'acte sexuel ou plutôt la séparation homme/femme ? Ou c'est volontairement flou ?

**Comment by nobrakal** [comment]
Moi j'avais des idées avec le prono sur internet (sortir les chiffres, comment ça marche... )

On a plus le temps de toute façon
